# Add 'feature' label to any changes within the 'src' folder
feature:
  - src/**/*

# Add 'tests' label to any changes within the 'tests' folder
tests:
  - tests/**/*

# Add 'documentation' label to any changes within the 'docs' or 'src/data' folder
documentation:
  - docs/**/*
  - src/data/**/*

# Add 'dependencies' label to any changes to 'package.json' or lock files
dependencies:
  - package.json
  - bun.lock

# Add 'ci' label to any changes within '.github'
ci:
  - .github/**/*
