# Add 'feature' label to any changes within the 'src' folder
feature:
  - any:
    - 'src/**/*'

# Add 'tests' label to any changes within the 'tests' folder
tests:
  - any:
    - 'tests/**/*'

# Add 'documentation' label to any changes within the 'docs' or 'src/data' folder
documentation:
  - any:
    - 'docs/**/*'
    - 'src/data/**/*'

# Add 'dependencies' label to any changes to 'package.json' or lock files
dependencies:
  - any:
    - 'package.json'
    - 'bun.lock'

# Add 'ci' label to any changes within '.github'
ci:
  - any:
    - '.github/**/*'
